services:
  mongo:
    image: mongo:latest
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      # - mongo_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

  server:
    build: ./server
    container_name: server
    restart: always
    ports:
      - "5000:5000"
    environment:
      - MONGO_URL=mongodb://mongo:27017/cat_and_mouse
    depends_on:
      - mongo

  client:
    build:
      context: ./client
      args:
        - VITE_API_URL=http://server:5000
    container_name: client
    restart: always
    ports:
      - "80:80"
    # environment:
    #   - VITE_API_URL=http://26.197.6.109:5000
    depends_on:
      - server

# volumes:
#   mongo_data: